---
title: "Animations"
author: "Ben Szeto"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}

data_ts<-read.csv("/Users/benszeto/Library/CloudStorage/OneDrive-Personal/Documents/US Elections/US Election Data/anes_timeseries_cdf_csv_20220916/anes_timeseries_cdf_csv_20220916.csv") #Mac

library(tidyverse)
library(gganimate)

```

```{r}


data_ts<-data_ts%>%
  mutate(Religion_Major_recode=case_when(VCF0128==1~"Protestant",
                                         VCF0128==2~"Catholic(Roman Catholic)",
                                         VCF0128==3~"Jewish",
                                         VCF0128==4~"Other and None",
                                         VCF0128==0~"Missing")
  )

Religion_Major_Year<-data_ts%>%
  mutate(Religion_Major_recode2=ifelse(Religion_Major_recode%in%c("Catholic(Roman Catholic)", "Protestant"), "Christian", Religion_Major_recode))%>%
  mutate(Religion_Major_recode2=factor(Religion_Major_recode2, c("Christian", "Jewish", "Other and None", "Missing")))%>%
           group_by(VCF0004,Religion_Major_recode2)%>%
           summarize(
    n()
  )%>%
  group_by(VCF0004)%>%
  mutate(percent=`n()`*100/sum(`n()`))


Religion_Major_Year%>%
  ggplot(aes(x=VCF0004, y=percent, color=Religion_Major_recode2))+
  geom_line()+
  geom_point()+
  theme_minimal()+
  labs(x="Year", y="Percent (%)", title="Trends in Religious Affiliation Among Americans Over Time", color="Religion")+
  transition_reveal(VCF0004) #make it animated

```


```{r}
data_ts<-data_ts%>%
  mutate(Church_Attendence_recode=case_when(VCF0130%in%c(1)~"Every Week",
                                            VCF0130%in%c(2,3)~"At least once a month",
                                            VCF0130%in%c(4)~"A few times a year",
                                            VCF0130%in%c(5,7)~"Never"
                                            
         ))


Church_Attendence_Year<-data_ts%>%
  filter(VCF0004>1970)%>%
  filter(Church_Attendence_recode%in%c("Every Week", "At least once a month", "A few times a year", "Never"))%>%
  mutate(Church_Attendence_recode=factor(Church_Attendence_recode, c("Every Week", "At least once a month", "A few times a year", "Never")))%>%
  group_by(VCF0004, Church_Attendence_recode)%>%
  summarize(
    n()
  )%>%
  group_by(VCF0004)%>%
  mutate(percent=`n()`*100/sum(`n()`))


Church_Attendence_Year%>%
  ggplot(aes(x=VCF0004, y=percent, color=Church_Attendence_recode))+
  geom_line()+
  geom_point()+
  labs(x="Year", y="Percent (%)", title="Church Attendence Over Time in the US", color="Church Attendence")+
  theme_minimal()+
  transition_reveal(VCF0004)

```
